name: release
on:
  workflow_dispatch:
    inputs:
      wkhtmltopdf_ref:
        description: 'Branch/Tag to use from the wkhtmltopdf/wkhtmltopdf repository'
        required: true
      packaging_release:
        description: 'Release to create in wkhtmltopdf/packaging repository'
        required: true
      packaging_iteration:
        description: 'Iteration (useful for tagged releases)'
        default: '1'
        required: true

jobs:
  windows:
    runs-on: windows-2019
    strategy:
      matrix:
        package_target:
          - msvc2015-win64
      fail-fast: false
    steps:
      - name: checkout packaging
        uses: actions/checkout@v2
        with:
          path: packaging
      - name: checkout wkhtmltopdf with submodules
        uses: actions/checkout@v2
        with:
          repository: wkhtmltopdf/wkhtmltopdf
          path: wkhtmltopdf
          submodules: true
          ref: ${{ github.event.inputs.wkhtmltopdf_ref }}
      - name: configure build environment
        run:  |
          choco install -yr --no-progress vcbuildtools -ia "/Full"
          pip install -q conan
          echo "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin" | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8
      - name: build
        run: cd packaging && python3 ./build vagrant ${{ matrix.package_target }} --clean --version - - --iteration ${{ github.event.inputs.packaging_iteration }} ../wkhtmltopdf
      - uses: softprops/action-gh-release@v0.1.14
        with:
          name: ${{ github.event.inputs.packaging_release }}
          tag_name: ${{ github.event.inputs.packaging_release }}-${{ github.event.inputs.packaging_iteration }}
          target_commitish: ${{ github.sha }}
          files: "packaging/wkhtmltox*.exe"
          fail_on_unmatched_files: false
          draft: true
          body: All packages were built and uploaded automatically as a part of [this run](${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}), using this [wkhtmltopdf branch/tag](https://github.com/wkhtmltopdf/wkhtmltopdf/tree/${{ github.event.inputs.wkhtmltopdf_ref }}).
